import os
import sys
import pandas as pd
import numpy as np

TARGET_COLUMN_NAME: str = "Result" #THE TARGET COLUMN NAME
PIPELINE_NAME: str = "NetworkSecurity_Pipeline" #THE PIPELINE NAME
ARTIFACT_DIR: str = "Artifacts" #THE ARTIFACT DIRECTORY NAME WHERE THE ARTIFACTS WILL BE STORED
FILE_NAME: str = "PhisingData.csv" #THE FILE NAME WHERE THE DATA WILL BE STORED
TRAIN_FILE_NAME: str="train.csv"#THE TRAIN FILE NAME WHERE THE TRAIN DATA WILL BE STORED
TEST_FILE_NAME: str="test.csv"#THE TEST FILE NAME WHERE THE TEST DATA WILL BE STORED




#DATA INGESTION RELATED CONSTANTS START WITH DATA_INGESTION VARIABLE NAME
DATA_INGESTION_COLLECTION_NAME: str = "NetworkSecurity_data" #THE COLLECTION NAME WHERE THE DATA(RAW DATA) WAS STORED IN MONGODB
DATA_INGESTION_DATABASE_NAME: str = "NetworkSecurity" #THE DATABASE NAME WHERE THE DATA(RAW DATA) WAS STORED IN MONGODB
DATA_INGESTION_DIR_NAME: str = "data_ingestion" #THE DIRECTORY NAME WHERE THE DATA WILL BE STORED
DATA_INGESTION_FEATURE_STORE_DIR: str = "feature_store" #THE FEATURE STORE DIRECTORY NAME WHERE THE DATA(RAW DATA) WILL BE STORED
DATA_INGESTION_INGESTED_DIR: str = "ingested" #THE INGESTED DIRECTORY NAME WHERE THE DATA(TRAIN AND TEST DATA) WILL BE STORED
DATA_INGESTION_TRAIN_TEST_SPLIT_RATIO: float = 0.2 #THE RATIO OF THE DATA THAT WILL BE USED FOR TRAINING AND TESTING SPLIT
DATA_INGESTION_FEATURE_NAME_DIR: str ="features_names"
DATA_INGESTION_FEATURES_NAME_FILE: str ="features_name.pkl"


#DATA VALIDATION RELATED CONSTANTS START WITH DATA_INGESTION VARIABLE NAME

DATA_VALIDATION_DIR: str="data_validation"
DATA_VALIDATION_VALID_DIR: str="valid_data"
DATA_VALIDATION_INVALID_DIR: str="invalid_data"
DATA_VALIDATION_DRIFT_REPORT_DIR: str="drift_report"
DATA_VALIDATION_DRIFT_REPORT_FILE_NAME: str="report.yaml"

SCHEMA_FILE_PATH: str=os.path.join("data_schema","schema.yaml")#THE SCHEMA FILE NAME WHERE THE SCHEMA WILL BE STORED




#DATA TRANSFORMATION RELATED CONSTANTS START WITH DATA_INGESTION VARIABLE NAME

DATA_TRANSFORMATION_DIR: str="data_transformation"
DATA_TRANSFORMATION_TRANSFORMED_DIR: str="transformed"
DATA_TRANSFORMATION_TRANSFORMED_OBJECT_DIR: str="transformed_object"
PREPROCESSOR_OBJECT_FILE_NAME: str="preprocessor.pkl"


#knn impute to handle missing values
DATA_TRANSFORMATION_IMPUTE_PARAMS: dict={
    "missing_values":np.nan,
    "n_neighbors":3,
    "weights":"uniform"
}

#MODEL TRAINER RELATED CONSTANTS START WITH MODEL_TRAINER VARIABLE NAME
MODEL_TRAINER_DIR: str="model_trainer"
MODEL_TRAINER_TRAINED_MODEL_DIR: str="trained_model"
MODEL_TRAINER_TRAINED_MODEL_NAME: str="model.pkl"
MODEL_TRAINER_EXPECTED_SCORE: float=0.6
MODEL_TRAINER_OVER_FIT_UNDER_FIT_THRESHOLD: float=0.05

MODEL_FILE_NAME: str="model.pkl"
SAVED_MODEL_DIR: str="saved_model"